// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4MQ4ZZVm-MAJuz0YCigfxAOFCPe-YwFM',
    appId: '1:675443611746:web:46486a79b732600e54593b',
    messagingSenderId: '675443611746',
    projectId: 'reddit-clone-61a1a',
    authDomain: 'reddit-clone-61a1a.firebaseapp.com',
    storageBucket: 'reddit-clone-61a1a.appspot.com',
    measurementId: 'G-L7C3382EN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaw-3pkLjJpAu924gXU7HFQxAzSqu02eM',
    appId: '1:675443611746:android:bfbb19dcaccbbcfe54593b',
    messagingSenderId: '675443611746',
    projectId: 'reddit-clone-61a1a',
    storageBucket: 'reddit-clone-61a1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACl35uDI38JejxnJqI2rHhg-IJzHCIP5o',
    appId: '1:675443611746:ios:3f790546397ccabd54593b',
    messagingSenderId: '675443611746',
    projectId: 'reddit-clone-61a1a',
    storageBucket: 'reddit-clone-61a1a.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4MQ4ZZVm-MAJuz0YCigfxAOFCPe-YwFM',
    appId: '1:675443611746:web:b0fa254f8927f93b54593b',
    messagingSenderId: '675443611746',
    projectId: 'reddit-clone-61a1a',
    authDomain: 'reddit-clone-61a1a.firebaseapp.com',
    storageBucket: 'reddit-clone-61a1a.appspot.com',
    measurementId: 'G-0QWDNBS48D',
  );
}
